api_app/urls/blueprints.py
from flask import Blueprint

index_bp = Blueprint('index', __name__)
channel_bp = Blueprint('channel', __name__)
auth_bp = Blueprint('auth', __name__)
static_bp = Blueprint('static', __name__)
error_bp = Blueprint('error', __name__)

class Blueprints(object):

    def __init__(self, app):
        self.app = app

    def register(self):
        from ..views import index_view
        self.app.register_blueprint(index_bp, url_prefix='')
        from ..views import auth_view
        self.app.register_blueprint(auth_bp, url_prefix='/auth')
        from ..views import channel_view
        self.app.register_blueprint(channel_bp, url_prefix='/channel')
        from ..views import static_view
        self.app.register_blueprint(static_bp, url_prefix='/static')
        from ..views import error_view
        self.app.register_blueprint(error_bp, url_prefix='/error')

        return self.app

api_app/views/auth_view.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from ..urls.blueprints import auth_bp
from flask import render_template, request, redirect, url_for, g, current_app, flash, jsonify, \
    session
from flask.ext.login import login_user, current_user, logout_user
from ..models.user import User
from db_init import db_query
from flask_user.views import _call_or_get, _endpoint_url, _send_registered_email, signals
from sqlalchemy.exc import IntegrityError
from flask_user.passwords import verify_password
from ..models.auth import RegisterSocNetwork
import datetime
from utils.client_utils import ajax_response
from sqlalchemy import or_
import json
import urllib
from oauth2client import client
from utils.openshift import get_app_url
import os
from exceptions import IOError


facebook = RegisterSocNetwork(service='facebook').get_service
vkontakte = RegisterSocNetwork(service='vkontakte')


@auth_bp.route('/login', methods=['POST'])
def login():
    """ Prompt for username/email and password and sign the user in."""
    user_manager = current_app.user_manager
    db_adapter = user_manager.db_adapter
    data = request.form
    next = request.args.get('next', _endpoint_url(user_manager.after_login_endpoint))
    reg_next = request.args.get('reg_next', _endpoint_url(user_manager.after_register_endpoint))

    # Immediately redirect already logged in users

    if _call_or_get(current_user.is_authenticated) and user_manager.auto_login_at_login:
        return redirect(next)
    user = None
    user_email = None

    # user = user_manager.find_user_by_username(data.get('user_name'))
    user = db_query(User).filter(or_(User.email == data.get('user_name'),
                                     User.username == data.get('user_name'))).first()
    if not user:
        return ajax_response(message="Ви ввели невірний логін або пароль")
    else:
        if user.password:
            if not verify_password(user_manager, data.get('password'), user.password):
                user = None
                return ajax_response(message="Ви ввели невірний логін або пароль")
        else:
            return ajax_response(message="Ви ввели невірний логін або пароль")
    user_email = None
    session['login_via'] = request.host
    remember_me = True if data.get('remember_me') else False
    if user and db_adapter.UserEmailClass:
        user_email = db_adapter.find_first_object(db_adapter.UserEmailClass,
                                                  user_id=int(user.get_id()), is_primary=True, )
    if not user and user_manager.enable_email:
        user, user_email = user_manager.find_user_by_email(data.get('user_name'))
    if user:
        _do_login_user(user, request.referrer, remember_me=remember_me)
    return ajax_response(message="Ви були успішно залоговані", reload_page = True)


@auth_bp.route('/logout')
def logout():

    logout_user()
    return redirect(url_for('index.index'))


@auth_bp.route('/register', methods=['POST'])
def register():
    """ Display registration form and create new User."""

    user_manager = current_app.user_manager
    db_adapter = user_manager.db_adapter
    # info = Info(username=request.form.get('username'), email=request.form.get('email'),
    #             password=request.form.get('password'))
    # info.save()

    # next = request.args.get('next', _endpoint_url(user_manager.after_login_endpoint))
    reg_next = request.args.get('reg_next', _endpoint_url(user_manager.after_register_endpoint))
    # invite token used to determine validity of registeree
    invite_token = request.values.get("token")

    # require invite without a token should disallow the user from registering
    # if user_manager.require_invitation and not invite_token:
    #     flash("Registration is invite only", "error")
    #     return redirect(url_for('user.login'))

    user_invite = None
    # if invite_token and db_adapter.UserInvitationClass:
    #     user_invite = db_adapter.find_first_object(db_adapter.UserInvitationClass, token=invite_token)

    if request.method == 'POST':
        # Create a User object using Form fields that have a corresponding User field
        User = db_adapter.UserClass
        user_class_fields = User.__dict__
        user_fields = {}

        # Create a UserEmail object using Form fields that have a corresponding UserEmail field
        if db_adapter.UserEmailClass:
            UserEmail = db_adapter.UserEmailClass
            user_email_class_fields = UserEmail.__dict__
            user_email_fields = {}

        # Create a UserAuth object using Form fields that have a corresponding UserAuth field
        if db_adapter.UserAuthClass:
            UserAuth = db_adapter.UserAuthClass
            user_auth_class_fields = UserAuth.__dict__
            user_auth_fields = {}

        # Enable user account
        if db_adapter.UserProfileClass:
            if hasattr(db_adapter.UserProfileClass, 'active'):
                user_auth_fields['active'] = True
            elif hasattr(db_adapter.UserProfileClass, 'is_enabled'):
                user_auth_fields['is_enabled'] = True
            else:
                user_auth_fields['is_active'] = True
        else:
            if hasattr(db_adapter.UserClass, 'active'):
                user_fields['active'] = True
            elif hasattr(db_adapter.UserClass, 'is_enabled'):
                user_fields['is_enabled'] = True
            else:
                user_fields['is_active'] = True
        data = request.form
        # For all form fields
        user_fields['registered_via'] = request.args
        for field_name, field_value in data.items():
            # Hash password field
            if field_name == 'password':
                if len(field_value) < 7:
                    return ajax_response(message='Пароль повинен містити не менше семи символів')
                hashed_password = user_manager.hash_password(field_value)
                if db_adapter.UserAuthClass:
                    user_auth_fields['password'] = hashed_password
                else:
                    user_fields['password'] = hashed_password
            # Store corresponding Form fields into the User object and/or UserProfile object
            else:
                if field_name in user_class_fields:
                    user_fields[field_name] = field_value
                if db_adapter.UserEmailClass:
                    if field_name in user_email_class_fields:
                        user_email_fields[field_name] = field_value
                if db_adapter.UserAuthClass:
                    if field_name in user_auth_class_fields:
                        user_auth_fields[field_name] = field_value

        # Add User record using named arguments 'user_fields'
        user = db_adapter.add_object(User, **user_fields)
        if db_adapter.UserProfileClass:
            user_profile = user

        # Add UserEmail record using named arguments 'user_email_fields'
        if db_adapter.UserEmailClass:
            user_email = db_adapter.add_object(UserEmail, user=user, is_primary=True, **user_email_fields)
        else:
            user_email = None

        # Add UserAuth record using named arguments 'user_auth_fields'
        if db_adapter.UserAuthClass:
            user_auth = db_adapter.add_object(UserAuth, **user_auth_fields)
            if db_adapter.UserProfileClass:
                user = user_auth
            else:
                user.user_auth = user_auth

        require_email_confirmation = True
        if user_invite:
            if user_invite.email == data.get('email'):
                require_email_confirmation = False
                db_adapter.update_object(user, confirmed_at=datetime.datetime.utcnow())

        try:
            db_adapter.commit()
        except IntegrityError as e:
            if e.message.find('email') != -1:
                return ajax_response(message='Така електронна адреса вже зареєстрована на нашому сайті')
            elif e.message.find('username') != -1:
                return ajax_response(message='Юзер з таким ніком вже зареєстрований на нашому сайті.'
                                             'Виберіть інший нік')

        # Send 'registered' email and delete new User object if send fails
        if user_manager.send_registered_email:
            try:
                # Send 'registered' email
                _send_registered_email(user, user_email, require_email_confirmation)

            except Exception as e:
                # delete new User object if send  fails
                db_adapter.delete_object(user)
                db_adapter.commit()
                raise

        # Send user_registered signal
        signals.user_registered.send(current_app._get_current_object(), user=user,
                                     user_invite=user_invite)

        # Redirect if USER_ENABLE_CONFIRM_EMAIL is set
        if user_manager.enable_confirm_email and require_email_confirmation:
            next = request.args.get('next', _endpoint_url(user_manager.after_register_endpoint))
            return ajax_response(message='На вашу електронну адресу був відправленний лист з підтвердженням реєстрації.'
                                         'Перейдіть на вашу поштову скриньку, щоб завершити реєстрацію на нашому '
                                         'сайті.<h5><a href="{mail_url}" target="_blank">Перейти</a></h5>"Якщо лист не прийшов '
                                         'перейдіть за <a href="{resend_email}">цим</a> посиланням і ми '
                                         'відправимо лист ще раз'.format(
                                          mail_url='http://'+data.get('email').split('@')[-1]+'/mail',
                                          resend_email=url_for('user.resend_confirm_email')),
                                 alert='На вашу електронну адресу був відправленний лист з підтвердженням реєстрації.'

api_app/templates/flask_user/change_password.html
{% extends 'flask_user/member_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}


<form action="" method="POST" class="form_user" role="form">
<h1>Змінити пароль</h1>
    {{ form.hidden_tag() }}
    {{ render_field(form.old_password, tabindex=10, label='Старий пароль') }}
    {{ render_field(form.new_password, tabindex=20, label='Новий пароль') }}
    {% if user_manager.enable_retype_password %}
        {{ render_field(form.retype_password, tabindex=30, label='Повторіть пароль') }}
    {% endif %}
    {{ render_submit_field(form.submit, tabindex=90, label='Змінити пароль') }}
</form>

{% endblock %}

api_app/templates/flask_user/change_username.html
{% extends 'flask_user/member_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}


<form action="" method="POST" class="form_user" role="form">
<h1>Змінити логін</h1>
    {{ form.hidden_tag() }}
    {{ render_field(form.new_username, tabindex=10, label='Новий логін') }}
    {{ render_field(form.old_password, tabindex=20, label='Пароль') }}
    {{ render_submit_field(form.submit, tabindex=90, label='Змінити логін') }}
</form>

{% endblock %}

api_app/templates/flask_user/flask_user_base.html
{% extends "base.html" %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-6 col-lg-5 col-centered">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

api_app/templates/flask_user/forgot_password.html
{% extends 'flask_user/public_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
<h1>{%trans%}Забули пароль{%endtrans%}</h1>

<form action="" method="POST" class="form_user" role="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.email, tabindex=10) }}
    {{ render_submit_field(form.submit, tabindex=90) }}
</form>

{% endblock %}

api_app/templates/flask_user/invite.html
{% extends 'flask_user/member_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
<h1>{%trans%}Invite User{%endtrans%}</h1>

<form action="" method="POST" class="form" role="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.email, tabindex=10) }}
    {{ render_submit_field(form.submit, tabindex=90) }}
</form>

{% endblock %}

api_app/templates/flask_user/login.html
{% extends 'flask_user/public_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}

<div class="row">
<div class="col-sm-6">

<h1>{%trans%}Sign in{%endtrans%}</h1>

{# ** Login form ** #}
<form action="{{ url_for('user.login') }}" method="POST" class="form" role="form">
    {{ login_form.hidden_tag() }}

    {# Username or Email #}
    {% set field = login_form.username if user_manager.enable_username else login_form.email %}
    {{ render_field(field, tabindex=110) }}

    {# Password #}
    {{ render_field(login_form.password, tabindex=120) }}

    {# Remember me #}
    {% if user_manager.enable_remember_me %}
    {{ render_checkbox_field(login_form.remember_me, tabindex=130) }}
    {% endif %}

    {# Submit button #}
    {{ render_submit_field(login_form.submit, tabindex=180) }}
</form>
    {% if user_manager.enable_forgot_password %}
        <p>
            <br/>
            <a href="{{ url_for('user.forgot_password') }}" tabindex='190'>
            {%trans%}Forgot your Password?{%endtrans%}</a>
        </p>
    {% endif %}

</div>
<div class="col-sm-6">

<h1>{%trans%}Register{%endtrans%}</h1>

{# ** Register form ** #}
<form action="{{ url_for('user.register') }}" method="POST" novalidate formnovalidate class="form" role="form">
    {{ register_form.hidden_tag() }}

    {# Username or Email #}
    {% set field = register_form.username if user_manager.enable_username else register_form.email %}
    {{ render_field(field, tabindex=210) }}

    {% if user_manager.enable_email and user_manager.enable_username %}
        {{ render_field(register_form.email, tabindex=220) }}
    {% endif %}

    {{ render_field(register_form.password, tabindex=230) }}

    {% if user_manager.enable_retype_password %}
        {{ render_field(register_form.retype_password, tabindex=240) }}
    {% endif %}

    {{ render_submit_field(register_form.submit, tabindex=280) }}
</form>

</div>
</div>
{% endblock %}

api_app/templates/flask_user/login_or_register.html
{% extends 'flask_user/public_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}

<div class="row">
<div class="col-sm-6">

<h1>{%trans%}Увійдіть{%endtrans%}</h1>

{# ** Login form ** #}
<form action="{{ url_for('user.login') }}" method="POST" class="form" role="form">
    {{ login_form.hidden_tag() }}

    {# Username or Email #}
    {% set field = login_form.username if user_manager.enable_username else login_form.email %}
    {{ render_field(field, tabindex=110) }}

    {# Password #}
    {{ render_field(login_form.password, tabindex=120) }}

    {# Remember me #}
    {% if user_manager.enable_remember_me %}
    {{ render_checkbox_field(login_form.remember_me, tabindex=130) }}
    {% endif %}

    {# Submit button #}
    {{ render_submit_field(login_form.submit, tabindex=180) }}
</form>
    {% if user_manager.enable_forgot_password %}
        <p>
            <br/>
            <a href="{{ url_for('user.forgot_password') }}" tabindex='190'>
            {%trans%}Forgot your Password?{%endtrans%}</a>
        </p>
    {% endif %}

</div>
<div class="col-sm-6">

<h1>{%trans%}Зареєструйтесь{%endtrans%}</h1>

{# ** Register form ** #}
<form action="{{ url_for('user.register') }}" method="POST" novalidate formnovalidate class="form" role="form">
    {{ register_form.hidden_tag() }}

    {# Username or Email #}
    {% set field = register_form.username if user_manager.enable_username else register_form.email %}
    {{ render_field(field, tabindex=210) }}

    {% if user_manager.enable_email and user_manager.enable_username %}
        {{ render_field(register_form.email, tabindex=220) }}
    {% endif %}

    {{ render_field(register_form.password, tabindex=230) }}

    {% if user_manager.enable_retype_password %}
        {{ render_field(register_form.retype_password, tabindex=240) }}
    {% endif %}

    {{ render_submit_field(register_form.submit, tabindex=280) }}
</form>

</div>
</div>
{% endblock %}

api_app/templates/flask_user/login_register_modal.html
   <script>
      $(function () {

        $('#loginform').on('submit', function (e) {
            var submit_button = document.getElementById("login_button_submit");
            var loading_login = document.getElementById("loading_login");
            submit_button.disabled = true;
            loading_login.hidden=false;
          e.preventDefault();

          $.ajax({
            type: 'post',
            url: '{{ url_for('auth.login') }}',
            data: $('#loginform').serialize(),
            success: function (data) {
                submit_button.disabled = false;
                loading_login.hidden=true;
                $('#message').html(data.message);
                if(data.alert){alert(data.alert)}
                if(data.reload_page){
                    location.reload()
                }
            }

          });

        });

      });

      $(function () {

        $('#registerform').on('submit', function (e) {
            var loading_login = document.getElementById("loading_register");
            var submit_button = document.getElementById("register_button_submit");
            submit_button.disabled = true;
            loading_login.hidden = false;
            password = $('#password').val();
          e.preventDefault();
            if(password !=$('#passwordReply').val()){
                $('#message').html('Паролі не співпадають. Попробуйте ще раз.');
                submit_button.disabled = false;
                loading_login.hidden = true;

            }
            else if(password.length<7){
                $('#message').html('Пароль повинен містити не менше семи символів.');
                            submit_button.disabled = false;
                            loading_login.hidden = true;

            }
            else{
                $.ajax({
            type: 'post',
            url: '{{ url_for('auth.register') }}',
            data: $('#registerform').serialize(),
            success: function (data) {
                submit_button.disabled = false;
                loading_login.hidden = true;
                $('#message').html(data.message);
                if(data.alert){alert(data.alert)}
            }

          });}


        });

      });

    </script>
<style>
    .nav-tabs {
    margin-bottom: 15px;
}
.sign-with {
    margin-top: 25px;
    padding: 20px;
}
div#OR {
    height: 30px;
    width: 30px;
    border: 1px solid #C2C2C2;
    border-radius: 50%;
    font-weight: bold;
    line-height: 28px;
    text-align: center;
    font-size: 12px;
    float: right;
    position: absolute;
    right: -16px;
    top: 40%;
    z-index: 1;
    background: #DFDFDF;
}
#message {
    color: #d9534f;
    background-color: rgba(0, 139, 209, 0.3);
    border-radius: 3px;
}
/* Hiding the checkbox, but allowing it to be focused */
.badgebox
{
    opacity: 0;
}

.badgebox + .badge
{
    /* Move the check mark away when unchecked */
    text-indent: -999999px;
    /* Makes the badge's width stay the same checked and unchecked */
	width: 27px;
}

.badgebox:focus + .badge
{
    /* Set something to make the badge looks focused */
    /* This really depends on the application, in my case it was: */

    /* Adding a light border */
    box-shadow: inset 0px 0px 5px;
    /* Taking the difference out of the padding */
}

.badgebox:checked + .badge
{
    /* Move the check mark back when checked */
	text-indent: 0;
}
</style>


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="/static/bootstrap3.3.0/dist/css/bootstrap.css">

<!-- Optional theme -->

<!-- Latest compiled and minified JavaScript -->
<script src="/static/bootstrap3.3.0/dist/js/bootstrap.min.js"></script>

<script>$('#myModal').modal('show');</script>
<!-- Large modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    ×</button>
                <h4 class="modal-title" id="myModalLabel">
                    Увійти/Зареєструватися</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8" style="border-right: 1px dotted #C2C2C2;padding-right: 30px;">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" id="nav_modify">
                            <li class="active"><a href="#Login" data-toggle="tab">Увійти</a></li>
                            <li class="non_active"><a href="#Registration" data-toggle="tab">Реєстрація</a></li>
                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div class="tab-pane active" id="Login">
                                <form role="form" class="form-horizontal" id="loginform">
                                <div class="form-group">
                                    <label for="email" class="col-sm-2 control-label_modify_tvonline">
                                        Логін</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="email" placeholder="Логін" name="user_name" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1" class="col-sm-2 control-label_modify_tvonline">
                                        Пароль</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль" name="password" />
                                    </div>
                                </div>
                                <div class="row">

                                    <div class="col-sm-10">
                                        <button type="submit" class="btn_checkbox btn-primary btn-sm" id="login_button_submit">
                                            Увійти</button>


 <label for="primary" class="btn_checkbox btn-primary">Запам'ятати пароль?<input type="checkbox" id="primary" class="badgebox" checked name="remember_me"><span class="badge">&check;</span></label>
                            </div>

                                </div>
                                  <i hidden class="fa fa-spinner fa-pulse fa-2x fa-fw" id="loading_login" style="color: #006699; position: fixed; margin-top: -32px; margin-left: 280px"></i>
                                </form>


                                <form>
                                <div class="row"> <div class="col-sm-10">
                                        <a href="{{ url_for('user.forgot_password') }}">Забули пароль?</a>
                                    </div> </div></form>

                            </div>
                            <div class="tab-pane" id="Registration">
                                <form role="form" class="form-horizontal" id="registerform">
                                <div class="form-group">
                                    <label for="name" class="col-sm-2 control-label_modify_tvonline name_register_form">
                                        Логін</label>
                                    <div class="col-sm-10">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <select class="form-control">
                                                    <option>Чл</option>
                                                    <option>Жн</option>
                                                </select>
                                            </div>
                                            <div class="col-md-9">
                                                <input type="text" id="name" class="form-control" name="username" placeholder="Логін" required/>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="email1" class="col-sm-2 control-label_modify_tvonline">
                                        Email</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="email1" name="email" placeholder="Електронна адреса" required/>
                                    </div>
                                </div>
                                    <div class="form-group">
                                    <label for="shown_name" class="col-sm-2 control-label_modify_tvonline">
                                        Нік</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="shown_name" name="shown_name" placeholder="Відображаюче ім'я" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-sm-2 control-label_modify_tvonline">
                                        Пароль</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Пароль" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-sm-2 control-label_modify_tvonline password_register_form">
                                        Повторіть пароль</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="passwordReply" name="passwordReply" placeholder="Введіть пароль ще раз" required/>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-2">
                                    </div>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary btn-sm" id="register_button_submit">
                                            Зареєструватися</button>
                                                                    </div>
                                </div>
                                    <i hidden class="fa fa-spinner fa-pulse fa-2x fa-fw" id="loading_register" style="color: #006699; position: fixed; margin-top: -32px; margin-left: 220px"></i>
                                </form>

                            </div>
                        </div>
                        <div id="OR" class="hidden-xs">
                            АБО</div>
                    </div>
                    <div class="col-md-4">
                        <div class="row text-center sign-with">
                            <div class="col-md-12">
                                <h3>
                                    Увійти за допомогою</h3>
                            </div>

                            <div class="col-md-12">
                                <div class="btn-group btn-group-justified">
                                    <a href="{{ url_for('auth.vkontakte_login') }}" class="btn btn-primary">Vkontakte</a>
                                    <a href="{{ url_for('auth.google_login') }}" class="btn btn-danger">Google</a>
                                </div>
                                <div class="btn-group btn-group-justified">
                                    <a href="{{ url_for('auth.facebook_login') }}" class="btn btn-primary">Facebook</a>
                                </div>
                            </div>
                        </div>
                        <div style="width: 85%; margin-left: 7%" id="message" align="center"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

api_app/templates/flask_user/manage_emails.html
{% extends 'flask_user/member_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
<h1>{%trans%}Manage Emails{%endtrans%}</h1>

<table class="table">
<tr><th>Email</th><th>Status</th><th>Actions</th></tr>
{% for user_email in user_emails %}
    <tr>
        <td>{{ user_email.email }}</td>
        <td>
            {% if user_email.confirmed_at %}
                Confirmed
            {% else %}
                <a href="{{ url_for('user.email_action', id=user_email.id, action='confirm') }}">Confirm Email</a>
            {% endif %}
        </td>
        <td>
            {% if user_email.is_primary %}
                <b>Primary email</b>
            {% else %}
                {% if user_email.confirmed_at %}
                    <a href="{{ url_for('user.email_action', id=user_email.id, action='make-primary') }}">Make primary</a> |
                {% endif %}
                <a href="{{ url_for('user.email_action', id=user_email.id, action='delete') }}">Delete</a>
            {% endif %}
        </td>
    </tr>
{% endfor %}
</table>

<form action="" method="POST" class="form" role="form">
    {{ form.hidden_tag() }}
    {{ render_field(form.email) }}
    {{ render_submit_field(form.submit) }}
</form>

{% endblock %}

api_app/templates/flask_user/member_base.html
{% extends 'flask_user/flask_user_base.html' %}